config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users do
    get '/users/sign_out', to: 'devise/sessions#destroy'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :posts do
    resources :comments
    
    member do
      get 'like'
    end
  end
  resources :comments do
    resources :comments
  end
  resources :feedbacks
  resources :notifications, only: [:index] do
    member do
      get 'mark_as_read'
    end
  end


  
  root 'posts#index'
  
  get '/about', to: 'pages#about'
  get '/userlist', to: 'pages#userlist'
  get '/faq', to: 'pages#faq' 

  get '/tech', to: 'posts#tech'
  get '/programming', to: 'posts#programming'
  get '/culture', to: 'posts#culture'
 
  get '/politics', to: 'posts#politics'
  get '/entertainment', to: 'posts#entertainment'
  
  get '/sports', to: 'posts#sport'
  get '/product', to: 'posts#product'
  get '/other', to: 'posts#other'

  get '/myposts', to: 'posts#myposts'
  
end

app/models/comment.rb
class Comment < ApplicationRecord
	

	belongs_to :commentable, polymorphic: true
  	has_many :comments, as: :commentable, dependent: :destroy
  	belongs_to :user
  	belongs_to :post

  	
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :find_commentable

    def new
      @comment = Comment.new
    end

    def create
      @comment = @commentable.comments.new comment_params
      @comment.user_id = current_user.id
      if params[:post_id]
        @comment.post_id = params[:post_id]
      else
        @comment.post_id = Comment.where(commentable_id: @commentable.commentable_id).first.post_id
      end
      if @comment.save
        flash[:notice]= 'Your comment was successfully posted!'
        Post.find_by_id(@comment.post_id).decrement!(:count)
        redirect_back fallback_location: root_path
      else
      	flash[:notice]= "Your comment wasn't posted!"
        redirect_back fallback_location: root_path
      end
      if Post.find_by_id(@comment.post_id).user!=current_user
        Notification.create(recipient: Post.find_by_id(@comment.post_id).user, actor: current_user, action: 'posted', notifiable: Post.find_by_id(@comment.post_id))
      end
    end

  def destroy
		@comment=Comment.find(params[:id])
    Post.find_by_id(@comment.post_id).decrement!(:count)
    @comment.destroy

    redirect_back fallback_location: root_path
	end

    private

    def comment_params
      params.require(:comment).permit(:body,:user_id,:post_id)
    end

    def find_commentable
      @commentable = Comment.find_by_id(params[:comment_id]) if params[:comment_id]
      @commentable = Post.find_by_id(params[:post_id]) if params[:post_id]
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<li>
<div class="card my-4">
	<div class="card-header">
<table>
	<tr>
		<td style="width:30px;">
			<% if !comment.user.avatar.blank? %>
				<img class="img-responsive" width="30" height="30" src=<%= image_path(comment.user.avatar.url(:thumb)) %> alt=<%= comment.user.avatar_file_name %>>
			<% else %>
				<img class="img-responsive" width="30" height="30" src=<%= image_path('default-missing.jpg') %> alt="default missing" >
			<% end %>
		</td>
		<td >

			<p style="font-size:20px;margin:0 15px;"><%= comment.body %></p>
		</td>
		<td align="right" style="width:30px;">
			<% if user_signed_in? && (current_user.id==1 || current_user.id==2 || comment.user.id== current_user.id || comment.post.user.id==current_user.id) %>
				<p><%= link_to image_tag(image_path('icon.png')),comment_path(comment), method: :delete, data: { confirm: "Are you sure you want to delete? "} %></p>
			<% end %>
		</td>
	</tr>
	<tr>
		<% if user_signed_in? %>
			<td style="width: 100%;" colspan="3"><small>Submitted <%= time_ago_in_words(comment.created_at) %> ago by <%= comment.user.name %>
				<% if (comment.user.id==1 || comment.user.id==2) %>
					<sup>Mod</sup>
				<% end %>
				
			</small></td>
		<% else %>
			<td colspan="2"><small>Submitted <%= time_ago_in_words(comment.created_at) %> ago by <%= comment.user.name %>
				<% if (comment.user.id==1 || comment.user.id==2) %>
					<sup>Mod</sup>
				<% end %>

			</small></td>
			<td><%= link_to "Reply",new_user_registration_path,class: "btn" %></td>
		<% end %>
	</tr>
</table>
</div> 
  
  
 <% if user_signed_in? %>
  
  	<%= form_for [comment, Comment.new] do |f| %>
  		<div class="card-body">
  			<div class="form-group" >
  				<%= f.text_area :body, placeholder: "Add a Reply", class: "form-control" %>
  			</div>
  		</div>
      <%= f.submit "Reply", class: "btn"  %>
    <% end %>
  
<% end %>
</div>
  <ul style="list-style-type: none">
      <%= render partial: 'comments/comment', collection: comment.comments %>
  </ul>

</li>

app/views/comments/index.html.erb
<div class="row">

            <!-- Blog Post Content Column -->
            <div class="col-lg-8">
            	<h1 class="page-header">
                    Feedback
                    <small>You are viewing feedbacks</small>
                </h1>

<% @comments.each do |comment| %>
<div style="border: 5px outset;padding:10px;margin:10px 0;">
	<h2 class="lead"><%= simple_format(comment.body) %></h2>
    <hr>
    <p><i class="fa fa-clock-o"></i> Posted on <%= comment.created_at.strftime("%B, %d %Y") %> By <%= comment.user.name %></p>
    <hr>
                <% if user_signed_in? && comment.user.id==4 %>
					<p align="left"><%= link_to image_tag("icon.png"), comment_path(comment), method: :delete, data: { confirm: "Are you sure?"} %></p>
                    <hr>
				<% end %>
</div>
    
	
<% end %>
<!-- Pager -->
<ul class="pager">
  <%= will_paginate @posts,:page_links => false,:previous_label=>"&larr; Older", :next_label=>"Newer &rarr;" %>
  
</ul>

</div>

<%= render 'partials/search' %>
<%= render 'partials/categories' %>
<%= render 'partials/widget' %>
</div>
            	
	
	
	