config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users do
    get '/users/sign_out', to: 'devise/sessions#destroy'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :posts do
    resources :comments
    
    member do
      get 'like'
    end
  end
  resources :comments do
    resources :comments
  end
  resources :feedbacks
  resources :notifications, only: [:index] do
    member do
      get 'mark_as_read'
    end
  end


  
  root 'posts#index'
  
  get '/about', to: 'pages#about'
  get '/userlist', to: 'pages#userlist'
  get '/faq', to: 'pages#faq' 

  get '/tech', to: 'posts#tech'
  get '/programming', to: 'posts#programming'
  get '/culture', to: 'posts#culture'
 
  get '/politics', to: 'posts#politics'
  get '/entertainment', to: 'posts#entertainment'
  
  get '/sports', to: 'posts#sport'
  get '/product', to: 'posts#product'
  get '/other', to: 'posts#other'

  get '/myposts', to: 'posts#myposts'
  
end

app/views/partials/_categories.html.erb
<!-- Blog Categories Well -->
                <div class="well">
                    <h4>Yourboard Categories</h4>
                    <div class="row">
                        <div class="col-lg-6">
                            <ul class="list-unstyled">
                                <li>
                                    <%= link_to tech_path do %>
                                        Science and Technology (<span><%= Post.where(category: "tech").count %></span>)
                                    <% end %>
                                    
                                </li>
                                <li>
                                    <%= link_to culture_path do %>
                                        Cultural (<span><%= Post.where(category: "culture").count %></span>)
                                    <% end %>
                                </li>
                                <li>
                                    <%= link_to entertainment_path do %>
                                        Entertainment (<span><%= Post.where(category: "Entertainment").count %></span>)
                                    <% end %>
                                </li>
                                <li>
                                    <%= link_to politics_path do %>
                                        Politics (<span><%= Post.where(category: "Politics").count %></span>)
                                    <% end %>
                                </li>
                            </ul>
                        </div>
                        <!-- /.col-lg-6 -->
                        <div class="col-lg-6">
                            <ul class="list-unstyled">
                                <li>
                                    <%= link_to sports_path do %>
                                        Sports (<span><%= Post.where(category: "Sports").count %></span>)
                                    <% end %>
                                </li>
                                <li>
                                    <%= link_to programming_path do %>
                                        Programming (<span><%= Post.where(category: "prog").count %></span>)
                                    <% end %>
                                </li>
                                <li>
                                    <%= link_to product_path do %>
                                        Products (<span><%= Post.where(category: "Product").count %></span>)
                                    <% end %>
                                </li>
                                <li>
                                    <%= link_to other_path do %>
                                        Others (<span><%= Post.where(category: "Other").count %></span>)
                                    <% end %>
                                </li>
                            </ul>
                        </div>
                        <!-- /.col-lg-6 -->
                    </div>
                    <!-- /.row -->
                </div>

app/views/partials/_footer.html.erb
<!-- Footer -->
    <hr>
    <footer class="py-5 bg-dark">
      <div class="container">

        <div class="row">
          
            <div class="col-lg-8 col-md-10 mx-auto">
            
              
            <!-- AddToAny BEGIN -->
<div class="a2a_kit a2a_kit_size_32 a2a_default_style">
<a class="a2a_dd" href="https://www.addtoany.com/share"></a>
<a class="a2a_button_facebook" data-toggle="tooltip" data-placement="top" title="Facebook"></a>
<a class="a2a_button_twitter" data-toggle="tooltip" data-placement="top" title="Twitter"></a>
<a class="a2a_button_google_plus" data-toggle="tooltip" data-placement="top" title="Google Plus"></a>
<a class="a2a_button_linkedin" data-toggle="tooltip" data-placement="top" title="Linked In"></a>
<a class="a2a_button_email" data-toggle="tooltip" data-placement="top" title="Email"></a>
<a class="a2a_button_whatsapp" data-toggle="tooltip" data-placement="top" title="Whatsapp"></a>
<a class="a2a_button_reddit" data-toggle="tooltip" data-placement="top" title="Reddit"></a>
<a class="a2a_button_blogger" data-toggle="tooltip" data-placement="top" title="Blogger"></a>
<a class="a2a_button_skype" data-toggle="tooltip" data-placement="top" title="Skype"></a>
<a class="a2a_button_sms" data-toggle="tooltip" data-placement="top" title="SMS"></a>
<a class="a2a_button_copy_link" data-toggle="tooltip" data-placement="top" title="Copy Link"></a>
<a class="a2a_button_google_gmail" data-toggle="tooltip" data-placement="top" title="Gmail"></a>
<a class="a2a_button_facebook_messenger" data-toggle="tooltip" data-placement="top" title="Facebook Messenger"></a>
<a class="a2a_button_hacker_news" data-toggle="tooltip" data-placement="top" title="Hacker News"></a>
<a class="a2a_button_outlook_com" data-toggle="tooltip" data-placement="top" title="Outlook"></a>
<a class="a2a_button_rediff" data-toggle="tooltip" data-placement="top" title="Rediff"></a>
<a class="a2a_button_yahoo_mail" data-toggle="tooltip" data-placement="top" title="Yahoo Mail"></a>
<a class="a2a_button_wechat" data-toggle="tooltip" data-placement="top" title="We Chat"></a>
</div>
<script>
var a2a_config = a2a_config || {};
a2a_config.linkname = "Yourboard";
a2a_config.linkurl = "http://yourboard.serveo.net";
</script>
<script async src="https://static.addtoany.com/menu/page.js"></script>
<!-- AddToAny END -->
          </div>
        </div>
        <p class="m-0 text-center text-white">Copyright &copy; Your Board 2018</p>
      </div>
      <!-- /.container -->
    </footer>
    

app/views/partials/_navbar.html.erb
<!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
      <div class="container">
        <%= link_to image_tag(image_path('logo2.png')),root_path, class: "navbar-brand" %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item" style="padding: 0 5px;font-size: 20px;">
              <%= link_to "Home",root_path, class: "nav-link my-nav" %>
            </li>
            <li class="nav-item" style="padding: 0 5px;font-size: 20px;" >
              <%= link_to "About", about_path, class: "nav-link my-nav" %>
            </li>
            <li class="nav-item dropdown" style="padding: 0 5px;font-size: 20px;">
              <a class="nav-link dropdown-toggle my-nav" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Categories
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <%= link_to "Science and Technology", tech_path, class: "dropdown-item" %>
                  <%= link_to "Cultural", culture_path, class: "dropdown-item" %>
                  <%= link_to "Entertainment", entertainment_path, class: "dropdown-item" %>
                  <%= link_to "Politics", politics_path, class: "dropdown-item" %>
                  <%= link_to "Sports", sports_path, class: "dropdown-item" %>
                  <%= link_to "Programming", programming_path, class: "dropdown-item" %>
                  <%= link_to "Products", product_path, class: "dropdown-item" %>
                  <%= link_to "Other", other_path, class: "dropdown-item" %>
                <div class="dropdown-divider"></div>
                <%= link_to "All Posts", root_path, class: "dropdown-item" %>
              </div>
            </li>
            <% if user_signed_in? %>
              <li class="nav-item" style="padding: 0 5px;font-size: 20px;">
                <%= link_to "Make Post", new_post_path, class: "nav-link my-nav" %>
              </li>
              <!-- Notification -->
              <li class="nav-item dropdown" data-behavior="notifications" style="padding: 0 5px;font-size: 20px;">
                <a class="nav-link dropdown-toggle my-nav" href="#" id="navbarDropdown3" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <i class="fa fa-bell" data-behavior="unread-count"></i>
                </a>

                <div class="dropdown-menu" id="notifications" data-behavior="notification-items" style="max-width: auto;max-height: 300px;overflow-y:auto;word-break: break-all;right:0;left:auto;">
                  
                  
                </div>
              </li>
              <!-- Notification end -->
              <li class="nav-item">
                <% if !current_user.avatar.blank? %>
                  <img class="img-responsive" style="border-radius: 25px;margin-left: 10px;" width="40px" height="40px" src=<%= image_path(current_user.avatar.url(:thumb)) %> alt=<%= current_user.avatar_file_name %>>
                <% else %>
                  <img class="img-responsive" style="border-radius: 25px;margin-left: 10px;" width="40px" height="40px" src=<%= image_path('default-missing.jpg') %> alt="missing">
                <% end %>
              </li>
              <li class="nav-item dropdown" style="padding: 0 5px;font-size: 20px;">
                <a class="nav-link dropdown-toggle my-nav" href="#" id="navbarDropdown2" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Profile
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown2">
                  <% xp = Comment.where(user: current_user).count*10 + Post.where(user: current_user).count*100 %>
                  <div class="dropdown-item"><p align="center" style="background-color: orange;color:black;font-weight: bold;font-size:18px;border-radius: 12px;margin-bottom:0;padding-bottom: 0;"><%= xp %> XP</p></div>
                  <div class="dropdown-divider"></div>
                  <%= link_to "My Posts", myposts_path, class: "dropdown-item" %>
                  <%= link_to "Make Post", new_post_path, class: "dropdown-item" %>
                  <%= link_to "Edit Account", edit_user_registration_path, class: "dropdown-item" %>
                  <%= link_to "Log Out",destroy_user_session_path, class: "dropdown-item",method: :get %> 
                </div>
              </li>
            <% else %>
              <li class="nav-item" style="padding: 0 5px;font-size: 20px;"> <%= link_to "Make Post", new_user_registration_path, class: "nav-link my-nav" %></li>
              <li class="nav-item dropdown" style="padding: 0 5px;font-size: 20px;">
                <a class="nav-link dropdown-toggle my-nav" href="#" id="navbarDropdown3" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Login/Sign Up
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown3">
                  <div class="col-sm-12">
                    <%= form_for(:user, :url => session_path(:user)) do |f| %>
                      <div class="form-group">
                        <%= f.label :email %>
                        <%= f.text_field :email, placeholder: "email@example.com", class: "form-control" %>
                      </div>
                      <div class="form-group">
                        <%= f.label :password %>
                        <%= f.password_field :password, placeholder: "Password", class: "form-control" %>
                      </div>
                      <!--<div class="form-check">
                        <%= f.check_box :remember_me, class: "form-check-input" %>
                        <%= f.label :remember_me %>
                      </div>-->
                      <%= f.submit 'Sign in',class: "btn btn-primary" %>
                      <div class="dropdown-divider"></div>
                      <%= render 'devise/shared/custom_login' %>
                    <% end %>
                  </div>
                </div>
              </li>

            <% end %>
            <li class="nav-item" style="padding: 0 5px;font-size: 20px;">
              <%= link_to "Feedback",feedbacks_path, class: "nav-link my-nav" %>
            </li>
            <% if user_signed_in? && (current_user.id==1 || current_user.id==2) %>
              <li class="nav-item" style="padding: 0 5px;font-size: 20px;">
                <%= link_to "User List",userlist_path, class: "nav-link my-nav" %>
              </li>
            <% end %>
            <li class="nav-item" style="padding: 0 5px;font-size: 20px;">
              <%= link_to "FAQs",faq_path, class: "nav-link my-nav" %>
            </li>
          </ul>
        </div>
      </div>
    </nav>

app/views/partials/_search.html.erb
<div class="col-md-4">
<!-- Blog Search Well -->
                <div class="well">
                    <h4>Yourboard Search</h4>
                    <%= form_tag(posts_path, method: :get) do %>
                    <div class="input-group">
                        
                        <%= text_field_tag :term, params[:term], placeholder: "Search for...", class: "form-control" %>
                        <span class="input-group-btn">
                            <!--<%= submit_tag 'Go', class: "btn btn-default" %>-->
                            <%= button_tag(type: 'submit', class: "btn btn-default") do %>
                             <i class="fa fa-search"></i>
                            <% end %>
                            
                        </span>
                        
                    </div>
                    <% end %>
                    <!-- /.input-group -->
                </div>

app/views/partials/_widget.html.erb
<!-- Side Widget Well -->
                <div class="well">
                    <h4>Recent Comments</h4>
                    <div id="RecentComments">
					<hr>	 
						<% Comment.order('created_at DESC').limit(5).each do |comment| %>
							 						    
							<%= link_to post_path(comment.post) do %>    
							      <table ><tr>
							      <td style="width:40px;">
							        <% if !comment.user.avatar.blank? %>
							          <img class="img-responsive" width="40" height="40" src=<%= image_path(comment.user.avatar.url(:thumb)) %> alt=<%= comment.user.avatar_file_name %>>
							        <% else %>
							          <img class="img-responsive" width="40" height="40" src=<%= image_path('default-missing.jpg') %> alt="default missing" >
							        <% end %>
							      </div>
							    </td>
							    <td>
							      <div > 
							        <p style="margin-left: 10px;font-size: 14px;"><%= comment.body.slice(0..50) %><strong> By <%= comment.user.name %>
							        	<% if (comment.user.id==1 || comment.user.id==2) %>
											<sup style="background-color:black;padding:1px 2px;border-radius:2px;color:white;font-weight:bold;">Mod</sup>
										<% end %>
							        </strong></p>
							      </div>
							    </td>
							    </tr>
							    </table> 
							<% end %>
							    <hr> 
						<% end %>
							  
						
					</div>
                </div>
                <div class="well">
                    <h4>Popular Posts</h4>
                    <div id="PopularPosts">
                    <hr>
						 <% Post.order('count DESC').limit(5).each do |post| %>
							 						    
							    <%= link_to post do %>
							      <table ><tr style="width:100%;">
							      <td style="padding-right:10px;"><div style="height:100%;width:100%;">
							        <% if !post.image.blank? %>
							          <img class="img-responsive" src=<%= image_path(post.image.url(:thumb)) %> alt=<%= post.image_file_name %>>
							        <% else %>
							          <img class="img-responsive" width="80" height="80" src=<%= image_path('no-image.jpg') %> alt="no image" >
							        <% end %>
							      </div>
							    </td>
							    <td style="width:60%;margin-left: 10px;padding-left:10px;font-size: 20px;border-left: 1px inset;">
							      <div > 
							        <p><%= post.title %><small><strong> By <%= post.user.name %></strong></small></p>
							      </div>
							    </td>
							    </tr>
							    </table> 
							  <% end %>
							  <hr> 
							    
							  
							  
							      
								
						<% end %>
						 
					</div>
                </div>
				
				<!-- Top users -->
				<div class="well">
                    <h4>Top Users</h4>
                    <div id="TopUsers">
                    <hr>
                    	<% point_hash = Hash.new %>
                    	<% User.all.each do |u| %>
							<% points = Comment.where(user: u).count*10 + Post.where(user: u).count*100 %>
							<% point_hash[u.name] = points %>
                    	<% end %>
                    	<% points_hash=Hash[point_hash.sort_by{|k, v| v}.reverse[0..4]] %>
                    	<% points_hash.each do |key,value| %>
                    		<table ><tr>
							      <td style="width:40px;">
							        <% if !User.find_by_id(User.where(name: key)).avatar.blank? %>
							          <img class="img-responsive" width="40" height="40" src=<%= image_path(User.find_by_id(User.where(name: key)).avatar.url(:thumb)) %> alt="x">
							        <% else %>
							          <img class="img-responsive" width="40" height="40" src=<%= image_path('default-missing.jpg') %> alt="default missing" >
							        <% end %>
							      </div>
							    </td>
							    <td>
									<div > 
							   			<p style="margin-left: 10px;font-size: 18px;"><strong><%= key %></strong> has <strong><%= value %></strong> XP</p>
									</div>
							    </td>
							</tr>
						</table>
                    		<hr>
						<% end %>
                    	
						
						 
					</div>
                </div>

                <!-- Top users close -->


                <% if user_signed_in? %>
	                <div class="well">
	                    <div class="card my-4">
	                    
						<%= form_for :feedback, url: feedbacks_path do |f| %>
							
								<h5 class="card-header"><%= f.label :body,"Give us Feedback:" %></h5>
								<div class="card-body">
									<div class="form-group">
										<%= f.text_area :body, class: "form-control" %>
								</div>
							
								<%= f.submit "Submit", class: "btn btn-primary" %>
								</div>
						<% end %>
						</div>
	                </div>
	            <% else %>
	            	<div class="well">
	                    <div class="card my-4">
	                    
						<%= form_for :feedback, url: feedbacks_path do |f| %>
							
								<h5 class="card-header"><%= f.label :body,"Give us Feedback:" %></h5>
								<div class="card-body">
									<div class="form-group">
										<%= f.text_area :body,placeholder: "Please Login or Sign Up to give feedback", class: "form-control" %>
								</div>
							
								<%= link_to "Login",new_user_session_path, class: "btn btn-primary" %>
								<%= link_to "Sign Up",new_user_registration_path, class: "btn btn-primary" %>
								</div>
						<% end %>
						</div>
	                </div>
                <% end %>
                </div>