config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users do
    get '/users/sign_out', to: 'devise/sessions#destroy'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :posts do
    resources :comments
    
    member do
      get 'like'
    end
  end
  resources :comments do
    resources :comments
  end
  resources :feedbacks
  resources :notifications, only: [:index] do
    member do
      get 'mark_as_read'
    end
  end


  
  root 'posts#index'
  
  get '/about', to: 'pages#about'
  get '/userlist', to: 'pages#userlist'
  get '/faq', to: 'pages#faq' 

  get '/tech', to: 'posts#tech'
  get '/programming', to: 'posts#programming'
  get '/culture', to: 'posts#culture'
 
  get '/politics', to: 'posts#politics'
  get '/entertainment', to: 'posts#entertainment'
  
  get '/sports', to: 'posts#sport'
  get '/product', to: 'posts#product'
  get '/other', to: 'posts#other'

  get '/myposts', to: 'posts#myposts'
  
end

app/models/feedback.rb
class Feedback < ApplicationRecord
	belongs_to :user
end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController
	before_action :find_feedback, only: [:destroy]
	
	def index
		@feedbacks=Feedback.all.order('created_at DESC').paginate(:page=> params[:page], :per_page=> 7)
	end

	def new
		@feedback=current_user.feedbacks.build
	end

	def create
		#@post=Post.find(params[:post_id])
		#@feedback=@post.feedbacks.create(params[:feedback].permit(:body))
		@feedback=current_user.feedbacks.build(feedback_params)
		@feedback.user_id = current_user.id
		@feedback.save
		flash[:notice] = "Thanks for feedback"
		redirect_to root_path

	end

	#def edit
	#end

	#def update
	#end

	#def show
	#end

	def destroy
		#@post=Post.find(params[:post_id])
		#@feedback=@post.feedbacks.find(params[:id])
		#@feedback.destroy
		#redirect_to post_path(@post)
		@feedback.destroy
		redirect_to feedbacks_path
	end

	private
		def find_feedback
			@feedback = Feedback.find(params[:id])
		end

		def feedback_params
			params.require(:feedback).permit(:body)
		end	
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/views/feedbacks/index.html.erb
<div class="row">

            <!-- Blog Post Content Column -->
            <div class="col-lg-8">
            	<h1 class="page-header">
                    Feedback
                    <small>You are viewing feedbacks</small>
                </h1>

<% @feedbacks.each do |feedback| %>
<div style="border: 5px outset;padding:10px;margin:10px 0;">
	<h2 class="lead"><%= simple_format(feedback.body) %></h2>
    <hr>
    <p><i class="fa fa-clock-o"></i> Posted on <%= feedback.created_at.strftime("%B, %d %Y") %> By <%= feedback.user.name %></p>
    <hr>
                <% if user_signed_in? && (current_user.id==1 || current_user.id==2) %>
					<p align="left"><%= link_to image_tag("icon.png"), feedback_path(feedback), method: :delete, data: { confirm: "Are you sure?"} %></p>
                    <hr>
				<% end %>
</div>
    
	
<% end %>
<!-- Pager -->
<ul class="pager">
  <%= will_paginate @posts,:page_links => false,:previous_label=>"&larr; Older", :next_label=>"Newer &rarr;" %>
  
</ul>

</div>

<%= render 'partials/search' %>
<%= render 'partials/categories' %>
<%= render 'partials/widget' %>
</div>
            	
	
	
	