config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users do
    get '/users/sign_out', to: 'devise/sessions#destroy'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :posts do
    resources :comments
    
    member do
      get 'like'
    end
  end
  resources :comments do
    resources :comments
  end
  resources :feedbacks
  resources :notifications, only: [:index] do
    member do
      get 'mark_as_read'
    end
  end


  
  root 'posts#index'
  
  get '/about', to: 'pages#about'
  get '/userlist', to: 'pages#userlist'
  get '/faq', to: 'pages#faq' 

  get '/tech', to: 'posts#tech'
  get '/programming', to: 'posts#programming'
  get '/culture', to: 'posts#culture'
 
  get '/politics', to: 'posts#politics'
  get '/entertainment', to: 'posts#entertainment'
  
  get '/sports', to: 'posts#sport'
  get '/product', to: 'posts#product'
  get '/other', to: 'posts#other'

  get '/myposts', to: 'posts#myposts'
  
end

app/models/post.rb
class Post < ApplicationRecord
	has_many :comments, as: :commentable, dependent: :destroy
	validates :title, presence: true, length: { minimum: 3 }
	validates :body, presence: true
	validates :category, presence: true
	#has_many :comments, dependent: :destroy #dependent: destroy for dependency of comment on post, if post is deleted than commment also delete 	
	belongs_to :user
	has_many :reports
	

	has_attached_file :image, styles: { medium: "50% x 50%>", thumb: "100x100>" }, default_url: "/images/:style/missing.png", validate_media_type: false
  	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  	def to_param
  		"#{id}-#{title.parameterize}"
	end 


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :find_doc, only: [:update, :destroy, :edit, :show, :like]
	
	def index
		#@posts=Post.where(user_id: current_user).order("created_at DESC")
		@posts = if params[:term] 
					Post.joins(:user).where('title LIKE :title1 OR body LIKE :body1 OR name LIKE :name1 OR email LIKE :email1',{:title1 => "%#{params[:term]}%", :body1 => "%#{params[:term]}%", :name1 => "%#{params[:term]}%", :email1 => "%#{params[:term]}%"}).all.order("updated_at DESC").paginate(:page=> params[:page], :per_page=> 5)
				else
					Post.all.order("updated_at DESC").paginate(:page=> params[:page], :per_page=> 3)
				end
		
		
	end

	def new
		@post=current_user.posts.build
	end

	def create
		@post=current_user.posts.build(post_params)

		if @post.save
			redirect_to @post
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		#if params[:image].blank?
		#	@post.image=nil
		#	@post.save
		#	if @post.update(post_params)
		#		redirect_to @post
		#	else
		#		render 'edit'
		#	end
		
		#else
		if @post.update(post_params)
			redirect_to @post
		else
			render 'edit'
		end
		#end
	end

	def show
		@post.increment!(:count)
	end

	def destroy
		@post.destroy
		redirect_to root_path
	end

	def like
		@post.increment!(:likes)
		@post.decrement!(:count)
		flash[:notice] = "You just liked the post"
		redirect_back fallback_location: root_path
	end

	def tech
		@posts= Post.where(category: "tech").all.order("updated_at DESC").paginate(:page=> params[:page], :per_page=> 5)
	end

	def programming
		@posts= Post.where(category: "prog").all.order("updated_at DESC").paginate(:page=> params[:page], :per_page=> 5)
	end

	def culture
		@posts= Post.where(category: "culture").all.order("updated_at DESC").paginate(:page=> params[:page], :per_page=> 5)
	end

	

	def politics
		@posts= Post.where(category: "Politics").all.order("updated_at DESC").paginate(:page=> params[:page], :per_page=> 5)
	end

	def entertainment
		@posts= Post.where(category: "Entertainment").all.order("updated_at DESC").paginate(:page=> params[:page], :per_page=> 5)
	end

	def sport
		@posts= Post.where(category: "Sports").all.order("updated_at DESC").paginate(:page=> params[:page], :per_page=> 5)
	end

	def product
		@posts= Post.where(category: "Product").all.order("updated_at DESC").paginate(:page=> params[:page], :per_page=> 5)
	end

	

	def other
		@posts= Post.where(category: "Other").all.order("updated_at DESC").paginate(:page=> params[:page], :per_page=> 5)		
	end

	def myposts
		@posts= Post.where(user_id: current_user.id).all.order("updated_at DESC").paginate(:page=> params[:page], :per_page=> 5)
	end


	private
		def find_doc
			@post = Post.find(params[:id])
			
		end

		def post_params
			params.require(:post).permit(:title,:body,:image,:category,:term,:spam,:slug)
		end

		

		

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_display.html.erb
<% @posts.each do |post| %>
  <div style="border: 5px outset;padding:10px;margin:10px 0; background-color: #edeff2" class="animated rubberBand">
    
    
      <h2>
          <%= link_to post.title, post %>
      </h2>
      <p class="lead">
          by <%= post.user.name %>
      </p>
      <p><i class="fa fa-clock-o"></i> Posted on <%= post.created_at.strftime("%B, %d %Y") %></p>
      
    <%= link_to post do %>
      <hr>
        <% if !post.image.blank? %>
          <img class="img-responsive" style="width:100%;padding: 0 10%;" src=<%= image_path(post.image.url) %> alt=<%= post.image_file_name %>>
        <% else %>
          <img class="img-responsive" style="padding: 0 10%;" src=<%= image_path('no-image.jpg') %> alt="no image" >
        <% end %>
      <hr>
        <p style="padding: 0 10%;font-size: 15px;font-weight:bold;"><%= sanitize(post.body.gsub(/<[^>]+>/,''), :tags=>[]).truncate(350, :separator => " ").html_safe %></p>
      
  <% end %>
  <hr> 
    <div>
      <%= link_to post, :class => 'btn btn-primary' do %>
        Read More<i class="fa fa-chevron-right"></i>
      <% end %>
      <p style="float:right;font-size: 15px;font-weight: bold;margin-left: 4px;">
        <i class="fa fa-heart"></i> <%= post.likes %>
      </p>
      <p style="float:right;font-size: 15px;font-weight: bold;margin-left: 4px;">
        <i class="fa fa-comment"></i> <%= Comment.where(post_id: post.id ).count %>
      </p>
      <p style="float:right;font-size: 15px;font-weight: bold;"><i class="fa fa-eye"></i> <%= post.count %> Hits</p>
    </div>
  
  </div>
      
	
<% end %>

app/views/posts/_disqus.html.erb
<div id="disqus_thread"></div>
<script>

/**
*  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
*  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/

var disqus_config = function () {
this.page.url = '<%= url_for(:only_path => false) %>';  // Replace PAGE_URL with your page's canonical URL variable
this.page.identifier = <%= @post.id %>; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
};

(function() { // DON'T EDIT BELOW THIS LINE
var d = document, s = d.createElement('script');
s.src = 'https://yourboard.disqus.com/embed.js';
s.setAttribute('data-timestamp', +new Date());
(d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
		<% if @post.errors.any? %>
			<div id="errors">
				<h2><%= pluralize(@post.errors.count, "error") %> stopped this post from saving</h2> 
				<ul>
					<% @post.errors.full_messages.each do |msg| %>
						<li><%= msg %></li>

					<% end %>

				</ul>

			</div>

		<% end %>
		<p>
			<%= f.label :category %><br>
			<%= f.select :category, [ ['Science and Technology','tech'], ['Programming','prog'], ['Culture','culture'],['Sports'],['Entertainment'],['Product'],['Politics'], 'Other' ], :prompt => 'Select One Category of your post', :class => 'genForm_dropBox' %>
		</p>
		<p>
			<%= f.label :title %><br>
			<%= f.text_field :title, autofocus: true,class: "form-control" %>
		</p>

		<p>
			<%= f.label :body %><br>
			<%= f.cktext_area :body, rows: 40 %>
		</p>

		<p>
			<%= f.label :image %><br>
			<%= f.file_field :image, class: "form-control" %>
		</p>

		

		<p>
			<% if !@post.image_file_name.blank? %>
				<%= image_tag @post.image.url(:thumb) %>
			<% end %>

		</p>

		<p>
			<%= f.submit class: "btn btn-primary" %>
		</p>
<% end %>

app/views/posts/culture.html.erb
<div class="row">

            <!-- Blog Entries Column -->
            <div class="col-md-8">
                
                <h1 class="page-header">
                    Cultural
                    <small>These are some cultural posts</small>
                </h1>
                <img class="img-responsive" src=<%= image_path('culture.jpg') %> alt="culture">
                <hr>
                

<%= render 'display' %>
<!-- Pager -->
<ul class="pager">
  <%= will_paginate @posts,:page_links => false,:previous_label=>"&larr; Older", :next_label=>"Newer &rarr;" %>
  
</ul>

</div>

<%= render 'partials/search' %>
<%= render 'partials/categories' %>
<%= render 'partials/widget' %>
</div>

app/views/posts/edit.html.erb
<div class="row">

            <!-- Blog Entries Column -->
            <div class="col-md-8">

                <h1 class="page-header">
                    Edit your Post
                    <small>Just clean it up</small>
                </h1>
	
	<%= render 'form' %>
	<%= link_to "Cancel", post_path, class: "btn btn-primary" %>

	
</div>

<%= render 'partials/search' %>
<%= render 'partials/categories' %>
<%= render 'partials/widget' %>
</div>

app/views/posts/entertainment.html.erb
<div class="row">

            <!-- Blog Entries Column -->
            <div class="col-md-8">
                
                <h1 class="page-header">
                    Entertainment
                    <small>These are some entertainment posts</small>
                </h1>
                <img class="img-responsive" src=<%= image_path('entertainment.jpg') %> alt="entertainment">
                <hr>

<%= render 'display' %>
<!-- Pager -->
<ul class="pager">
  <%= will_paginate @posts,:page_links => false,:previous_label=>"&larr; Older", :next_label=>"Newer &rarr;" %>
  
</ul>

</div>

<%= render 'partials/search' %>
<%= render 'partials/categories' %>
<%= render 'partials/widget' %>
</div>

app/views/posts/index.html.erb
 <% if !user_signed_in? && notice.nil? %>
	 <div id="ac-wrapper">
	  <div id="popup">
	  <center>
	    <span class="close-button" onclick="PopUp()" >&times;</span>
	    <h4>Please Sign Up to post your Post</h4>
	    <hr>
	    <table>
	    <%= form_for(:user, :url => registration_path(:user)) do |f| %>
	    	<tr>
	    	  <td><%= f.label :name %></td>
			  <td><%= f.text_field :name, required: true,autofocus: true,placeholder: "Name",class: "form-control" %></td>
			</tr>
		  	<tr>
	    	  <td><%= f.label :email %></td>
			  <td><%= f.email_field :email, required: true,placeholder: "email@example.com",class: "form-control" %></td>
			</tr>
			<tr>
	    	  <td><%= f.label :avatar,"Profile Pic" %></td>
			  <td><%= f.file_field :avatar, class: "form-control" %></td>
			</tr>
			<tr>
	    	  <td><%= f.label :timeline,"Timeline Pic" %></td>
			  <td><%= f.file_field :timeline,class: "form-control" %></td>
			</tr>
			<tr>
	    	  <td><%= f.label :password %></td>
			  <td><%= f.password_field :password, required: true,  hint: ("#{@minimum_password_length} characters minimum" if @minimum_password_length), placeholder: "6 characters minimum", class: "form-control" %></td>
			</tr>
		    <tr>
	    	  <td><%= f.label :password_confirmation %></td>
			  <td><%= f.password_field :password_confirmation, required: true, placeholder: "Confirmed Password", class: "form-control" %></td>
			</tr>
		    </table>
		   	
		  
			  <%= f.submit 'Sign Up',class: "btn btn-primary", onclick: "PopUp()" %>
			
			  <%= render 'devise/shared/custom_signup' %>
			
		<% end %>
	  </center>
	  </div>
	</div>
	<script type="text/javascript">
	function PopUp(){
	        document.getElementById('ac-wrapper').style.display="none"; 
	}
	$(document).ready(function(){
	   setTimeout(function(){
	      PopUp();
	   },50000000); // 5000 to load it after 5 seconds from page load
	});
	</script>
<% end %>
<div class="row">

            <!-- Blog Entries Column -->
            <div class="col-md-8">

                <h1 class="page-header">
                    Posts
                    <small>You can learn a lot</small>
                </h1>

                

<%= render 'display' %>
<!-- Pager -->
<ul class="pager">
  <%= will_paginate @posts,:page_links => false,:previous_label=>"&larr; Older", :next_label=>"Newer &rarr;" %>
  
</ul>

</div>

<%= render 'partials/search' %>
<%= render 'partials/categories' %>
<%= render 'partials/widget' %>
</div>

app/views/posts/myposts.html.erb
<div class="row">

            <!-- Blog Entries Column -->
            <div class="col-md-8">

                <h1 class="page-header">
                    My Posts
                    <small>Your posts</small>
                </h1>
<div style="position: relative;">
<% if !current_user.timeline.blank? %>   
  <img class="img-responsive" src=<%= image_path(current_user.timeline.url) %> alt=<%= current_user.timeline_file_name %>>
<% else %>  
  <img class="img-responsive" src=<%= image_path('home.png') %> alt="home">
<% end %>
<div id="profile">
<% if !current_user.avatar.blank? %>
  <img class="img-responsive" src=<%= image_path(current_user.avatar.url(:thumb)) %> alt=<%= current_user.avatar_file_name %>>
<% else %>
  <img class="img-responsive" src=<%= image_path('default-missing.jpg') %> alt="missing">
<% end %>
</div>

<div id="changetimeline">
  <%= link_to edit_user_registration_path do %>
    <button class="btn btn-primary">Change Time line Pic</button>
  <% end %>
</div>
</div>
<hr>

<%= render 'display' %>
<!-- Pager -->
<ul class="pager">
  <%= will_paginate @posts,:page_links => false,:previous_label=>"&larr; Older", :next_label=>"Newer &rarr;" %>
  

</div>

<%= render 'partials/search' %>
<%= render 'partials/categories' %>
<%= render 'partials/widget' %>
</div>

app/views/posts/new.html.erb
<div class="row">

            <!-- Blog Entries Column -->
            <div class="col-md-8">

                <h1 class="page-header">
                    Make Post
                    <small>Unleash your Thoughts</small>
                </h1>

	<%= form_for :post, url: posts_path do |f| %>
		<% if @post.errors.any? %>
			<div id="errors">
				<h2><%= pluralize(@post.errors.count, "error") %> stopped this post from saving</h2> 
				<ul>
					<% @post.errors.full_messages.each do |msg| %>
						<li><%= msg %></li>

					<% end %>

				</ul>

			</div>

		<% end %>
		<p>
			<%= f.label :category %><br>
			<%= f.select :category, [ ['Science and Technology','tech'], ['Programming','prog'], ['Culture','culture'],['Sports'],['Entertainment'],['Product'],['Politics'], 'Other' ], :prompt => 'Select One Category of your post', :class => 'genForm_dropBox' %>
		</p>
		<p>
			<%= f.label :title %><br>
			<%= f.text_field :title, autofocus: true,class: "form-control" %>
		</p>

		<p>
			<%= f.label :body %><br>
			<%= f.cktext_area :body, :rows=>40 %>
		</p>

		<p>
			<%= f.label :image %><br>
			<%= f.file_field :image, required: false, class: "form-control" %>
		</p>

		

		<p>
			<%= f.submit class: "btn btn-primary" %>
		</p>
	<% end %>
</div>

<%= render 'partials/search' %>
<%= render 'partials/categories' %>
<%= render 'partials/widget' %>
</div>

app/views/posts/politics.html.erb
<div class="row">

            <!-- Blog Entries Column -->
            <div class="col-md-8">
                
                <h1 class="page-header">
                    Political
                    <small>These are some political posts</small>
                </h1>
                <img class="img-responsive" src=<%= image_path('politics.jpg') %> alt="politics">
                <hr>

<%= render 'display' %>
<!-- Pager -->
<ul class="pager">
  <%= will_paginate @posts,:page_links => false,:previous_label=>"&larr; Older", :next_label=>"Newer &rarr;" %>
  
</ul>

</div>

<%= render 'partials/search' %>
<%= render 'partials/categories' %>
<%= render 'partials/widget' %>
</div>

app/views/posts/product.html.erb
<div class="row">

            <!-- Blog Entries Column -->
            <div class="col-md-8">
                
                <h1 class="page-header">
                    Product
                    <small>These are some products posts</small>
                </h1>
                <img class="img-responsive" src=<%= image_path('product.jpg') %> alt="product">
                <hr>

<%= render 'display' %>
<!-- Pager -->
<ul class="pager">
  <%= will_paginate @posts,:page_links => false,:previous_label=>"&larr; Older", :next_label=>"Newer &rarr;" %>
  
</ul>

</div>

<%= render 'partials/search' %>
<%= render 'partials/categories' %>
<%= render 'partials/widget' %>
</div>

app/views/posts/programming.html.erb
<div class="row">

            <!-- Blog Entries Column -->
            <div class="col-md-8">
                
                <h1 class="page-header">
                    Programming
                    <small>These are some programming posts</small>
                </h1>
                <img class="img-responsive" src=<%= image_path('programming.jpg') %> alt="programming">
                <hr>

<%= render 'display' %>
<!-- Pager -->
<ul class="pager">
  <%= will_paginate @posts,:page_links => false,:previous_label=>"&larr; Older", :next_label=>"Newer &rarr;" %>
  
</ul>

</div>

<%= render 'partials/search' %>
<%= render 'partials/categories' %>
<%= render 'partials/widget' %>
</div>

app/views/posts/show.html.erb
<div class="row">

            <!-- Blog Post Content Column -->
            <div class="col-lg-8">
            	<h1 class="page-header">
                    You are viewing a post
                </h1>
            		<div>
					<% if user_signed_in? && @post.user_id== current_user.id %>
						<%= link_to "Update", edit_post_path(@post), class: "btn btn-primary" %>
						<%= link_to "Delete", post_path(@post), method: :delete, data: { confirm: "Are you sure you want to delete? "}, class: "btn btn-primary" %>
                        <hr>
					<% end %>

					</div>
                    
            	<!-- Title -->
                <h1><%= @post.title %></h1>

                <!-- Author -->
                <p class="lead">
                    by <%= @post.user.name %>
                </p>

                <hr>

                <!-- Date/Time -->
                <p><i class="fa fa-clock-o"></i> Posted on <%= @post.created_at.strftime("%B, %d %Y") %></p>

                <hr>

                <!-- Preview Image -->
                <% if !@post.image_file_name.blank? %>
                	<img class="img-responsive" src=<%= @post.image.url %> alt=<%= @post.image_file_name %>>
                	<hr>
                <% end %>
                <h4 id="postbody"><%= @post.body.html_safe %></h4>
                
                <hr>
                <%= link_to like_post_path(@post.id) do %>
                    <span class="btn btn-primary">
                    <span style="font-size:20px;font-weight: bold;">Like the Post</span> <i class="fa fa-heart" style="font-size: 20px;font-weight: bold;"></i>
                    </span>
                <% end %>
                <hr>

                <p style="display:inline;font-size: 15px;font-weight: bold;margin-right:15px;">
                    <i class="fa fa-heart"></i> <%= @post.likes %> Upvotes
                </p>
      
                <p style="display:inline;font-size: 15px;font-weight: bold;"><i class="fa fa-eye"></i> <%= @post.count %> Hits</p>
                <hr>
	
	<!-- AddToAny BEGIN -->
<div class="a2a_kit a2a_kit_size_32 a2a_default_style">
<a class="a2a_dd" href="https://www.addtoany.com/share"></a>
<a class="a2a_button_facebook" data-toggle="tooltip" data-placement="top" title="Facebook"></a>
<a class="a2a_button_twitter" data-toggle="tooltip" data-placement="top" title="Twitter"></a>
<a class="a2a_button_google_plus" data-toggle="tooltip" data-placement="top" title="Google Plus"></a>
<a class="a2a_button_linkedin" data-toggle="tooltip" data-placement="top" title="Linked In"></a>
<a class="a2a_button_email" data-toggle="tooltip" data-placement="top" title="Email"></a>
<a class="a2a_button_whatsapp" data-toggle="tooltip" data-placement="top" title="Whatsapp"></a>
<a class="a2a_button_reddit" data-toggle="tooltip" data-placement="top" title="Reddit"></a>
<a class="a2a_button_blogger" data-toggle="tooltip" data-placement="top" title="Blogger"></a>
<a class="a2a_button_skype" data-toggle="tooltip" data-placement="top" title="Skype"></a>
<a class="a2a_button_sms" data-toggle="tooltip" data-placement="top" title="SMS"></a>
<a class="a2a_button_copy_link" data-toggle="tooltip" data-placement="top" title="Copy Link"></a>
<a class="a2a_button_hacker_news" data-toggle="tooltip" data-placement="top" title="Hacker News"></a>
</div>
<script async src="https://static.addtoany.com/menu/page.js"></script>
<!-- AddToAny END -->

	<hr style="margin-bottom: 5%;">

    <h3>Comments</h3>

<% if user_signed_in? %>
    <div class="card my-4">
        <%= form_for [@post, Comment.new] do |f| %>
            <h5 class="card-header"><%= f.label :body,"Leave a Comment:" %></h5>
            <div class="card-body">
                <div class="form-group">
                    <%= f.text_area :body, placeholder: "Add a comment",class: "form-control" %>
                </div>
            </div>
            <%= f.submit "Add Comment", class: "btn btn-primary" %>
        <% end %>
    </div>
<% end %>
<% if Comment.where(post_id: @post.id).count!=0 %>
    <div style="height: 600px;overflow: auto;">
            <ul style="list-style-type: none">
              <%= render(partial: 'comments/comment', collection: @post.comments) %>
            </ul>
    </div>
<% else %>
    <div><h4>No Comments Yet</h4></div>
<% end %>    
	
	</div>

<%= render 'partials/search' %>
<%= render 'partials/categories' %>
<%= render 'partials/widget' %>
</div>

	

app/views/posts/tech.html.erb
<div class="row">

            <!-- Blog Entries Column -->
            <div class="col-md-8">
                
                <h1 class="page-header">
                    Science and Technology
                    <small>These are some tech posts</small>
                </h1>
                <img class="img-responsive" src=<%= image_path('tech.jpg') %> alt="tech">
                <hr>

<%= render 'display' %>
<!-- Pager -->
<ul class="pager">
  <%= will_paginate @posts,:page_links => false,:previous_label=>"&larr; Older", :next_label=>"Newer &rarr;" %>
  
</ul>

</div>

<%= render 'partials/search' %>
<%= render 'partials/categories' %>
<%= render 'partials/widget' %>
</div>